### ISSUE TITLE
use github actions rather than travis

### ISSUE THREAD

**Issue by wfmackey** [grattan/R_at_Grattan#52]

**Comment by wfmackey** [comment]
@MattCowgill WE'RE BACK, BABY

**Comment by MattCowgill** [comment]
@wfmackey WOAH BLAST FROM THE PAST

**Comment by wfmackey** [comment]
Done via `deploy_bookdown.yaml` and the `gh-pages` branch. Edits to Rmd files (unbuilt) will be reflected in the website
